# Generated by Django 3.0.5 on 2020-11-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('place_name', models.CharField(default='', max_length=70)),
                ('place_addr', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=600)),
                ('writer', models.CharField(default='', max_length=70)),
                ('lat', models.FloatField(default=0.0)),
                ('lng', models.FloatField(default=0.0)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
